FROM node:16.14.1-alpine3.14

WORKDIR /rmq-ffmpeg

RUN apk add --no-cache curl && \
    curl -o- -L https://yarnpkg.com/install.sh | sh -s -- && \
    apk del curl && \
    export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

COPY package*.json ./
RUN yarn install --production

COPY . .

CMD ["yarn", "start"]